version: "3.2"
services:
  iam:
    image: ns/iam
    command: ["start-dev", "--spi-theme-static-max-age=-1", "--spi-theme-cache-themes=false", "--spi-theme-cache-templates=false"]
    ports:
      - "80:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_SPI_THEME_WELCOME_THEME: novasoftworks
    volumes:
      - type: bind
        source: ./themes/novasoftworks
        target: /opt/keycloak/themes/novasoftworks
