name: Docker Image - Continuous Integration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for deployment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
      version:
        description: 'Keycloak customization version'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} 
    env:
      VERSION: ${{ inputs.version }}
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    steps:
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Extract Keycloak version from Dockerfile
      id: keycloak-version
      run: echo "KEYCLOAK_VERSION=$(grep 'FROM quay.io/keycloak/keycloak:' Dockerfile | cut -d ':' -f 2)" >> $GITHUB_ENV
    - name: Setup Image Repository
      run: echo "IMAGE_REPOSITORY=$DOCKER_REGISTRY/nexus/keycloak" >> $GITHUB_ENV
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |-
          ${{ env.IMAGE_REPOSITORY }}:$KEYCLOAK_VERSION-$VERSION
          ${{ env.DOCKER_REGISTRY }}:latest
    - run: echo "### $IMAGE_REPOSITORY:$KEYCLOAK_VERSION-$VERSION published! :rocket:" >> $GITHUB_STEP_SUMMARY
